import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const henkenGrotesk = Hanken_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`henkenGrotesk.className`}
      >
        {children}
      </body>
    </html>
  );
}
